import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter/foundation.dart';

/// Registry to track the version of logic/features used to generate data.
/// This allows us to detect when data was generated by older logic and might need re-computation.
class FeatureVersionRegistry {
  static const String _paramPrefix = 'feature_version_';

  final SharedPreferences _prefs;

  FeatureVersionRegistry(this._prefs);

  /// Get the currently recorded version for a feature.
  /// Returns 0 if never recorded.
  int getVersion(String featureKey) {
    return _prefs.getInt('$_paramPrefix$featureKey') ?? 0;
  }

  /// Update the recorded version for a feature.
  Future<void> setVersion(String featureKey, int version) async {
    await _prefs.setInt('$_paramPrefix$featureKey', version);
    debugPrint('FeatureVersionRegistry: Updated $featureKey to v$version');
  }

  /// Check if a feature's data needs migration/re-computation.
  /// [currentLogicVersion] is the version of the code currently running.
  bool needsUpdate(String featureKey, int currentLogicVersion) {
    final int recorded = getVersion(featureKey);
    return recorded < currentLogicVersion;
  }
}
